version: "3.7"
services:
  keepslip-nginx:
    image: nginx:1.13.12-alpine
    container_name: keepslip-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.9

  keepslip-db:
    container_name: keepslip-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.10

  customer:
    container_name: customer
    restart: always
    build:
      context: ./Customer
    ports:
      - "3001:3001"
    depends_on:
      - keepslip-db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=KeepSlipDB
      - MYSQL_HOST=172.28.1.10
      - MYSQL_PORT=3306
    volumes:
      - /usr/src/app/node_modules
      - ./Customer/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.1

  store:
    container_name: store
    restart: always
    build:
      context: ./Store
    ports:
      - "3002:3002"
    depends_on:
      - keepslip-db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=KeepSlipDB
      - MYSQL_HOST=172.28.1.10
      - MYSQL_PORT=3306
    volumes:
      - /usr/src/app/node_modules
      - ./Store/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.2

  receipt:
    container_name: receipt
    restart: always
    build:
      context: ./Receipt
    ports:
      - "3003:3003"
    depends_on:
      - keepslip-db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=KeepSlipDB
      - MYSQL_HOST=172.28.1.10
      - MYSQL_PORT=3306
    volumes:
      - /usr/src/app/node_modules
      - ./Receipt/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.3

  smart-contract:
    container_name: smart-contract
    restart: always
    build:
      context: ./SmartContract
    ports:
      - "3004:3004"
    volumes:
      - /usr/src/app/node_modules
      - ./SmartContract/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.4

  the-revenue-department:
    container_name: the-revenue-department
    restart: always
    build:
      context: ./TheRevenueDepartment
    ports:
      - "3005:3005"
    volumes:
      - /usr/src/app/node_modules
      - ./TheRevenueDepartment/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.5

  receipt-from-store:
    container_name: receipt-from-store
    restart: always
    build:
      context: ./ReceiptFromStore
    ports:
      - "3006:3006"
    depends_on:
      - keepslip-db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=ReceiptDB
      - MYSQL_HOST=172.28.1.10
      - MYSQL_PORT=3306
    volumes:
      - /usr/src/app/node_modules
      - ./ReceiptFromStore/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.6

  auth:
    container_name: auth
    restart: always
    build:
      context: ./auth
    ports:
      - "3007:3007"
    depends_on:
      - keepslip-db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=KeepSlipDB
      - MYSQL_HOST=172.28.1.10
      - MYSQL_PORT=3306
    volumes:
      - /usr/src/app/node_modules
      - ./auth/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.7

  client:
    container_name: client
    restart: always
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - keepslip-db
    environment:
      - API_PATH=api.keepslip.com
    volumes:
      - /usr/src/app/.next
      - /usr/src/app/node_modules
      - ./client/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.8

networks:
  keepslip_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
# database (share volume in KeepSlip-Backend/data)
# docker run --rm --name keepslip-db -p 3306:3306 -v C:/Users/Surasith/Desktop/KeepSlip-Backend/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=1234 -d mysql
# docker exec -it keepslip-db bash
# mysql --user=root --password=1234
# ALTER USER root IDENTIFIED WITH mysql_native_password BY '1234';

# dockerfile customer
# docker inspect keepslip-db <--- to get ip of keepslip-db use to setting MYSQL_HOST
# or // docker inspect --format="{{json .NetworkSettings.Networks}}"  keepslip-db <--- to get ip of keepslip-db use to setting MYSQL_HOST
# docker run --rm -p 3001:3001 -e MYSQL_USER=root -e MYSQL_PASSWORD=1234 -e MYSQL_DATABASE=KeepSlipDB -e MYSQL_HOST=172.17.0.2 -e MYSQL_PORT=3306 --link keepslip-db --name=customer customer

# https://www.youtube.com/watch?v=tIbMSqTEpfY
# https://hub.docker.com/_/mysql
# https://docs.docker.com/compose/compose-file/#command

# NextJS with Docker and NGINX
# https://steveholgado.com/nginx-for-nextjs/
# https://www.google.com/search?q=next+js+nginx+docker&oq=next+js+nginx+docker&aqs=chrome..69i57.13128j1j7&sourceid=chrome&ie=UTF-8
