version: "3.7"
services:
  keepslip-nginx:
    image: nginx:1.13.12-alpine
    container_name: keepslip-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      keepslip_network:

  keepslip-db:
    container_name: keepslip-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.10

  service:
    container_name: service
    restart: always
    build:
      context: ./Service
    ports:
      - "3001:3001"
    depends_on:
      - keepslip-db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=KeepSlipDB
      - MYSQL_HOST=172.28.1.10
      - MYSQL_PORT=3306
    volumes:
      - /usr/src/app/node_modules
      - ./Service/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.1

  smart-contract:
    container_name: smart-contract
    restart: always
    build:
      context: ./SmartContract
    ports:
      - "3002:3002"
    volumes:
      - /usr/src/app/node_modules
      - ./SmartContract/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.2

  the-revenue-department:
    container_name: the-revenue-department
    restart: always
    build:
      context: ./TheRevenueDepartment
    ports:
      - "3003:3003"
    volumes:
      - /usr/src/app/node_modules
      - ./TheRevenueDepartment/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.3

  receipt-from-store:
    container_name: receipt-from-store
    restart: always
    build:
      context: ./ReceiptFromStore
    ports:
      - "3004:3004"
    depends_on:
      - keepslip-db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=ReceiptDB
      - MYSQL_HOST=172.28.1.10
      - MYSQL_PORT=3306
    volumes:
      - /usr/src/app/node_modules
      - ./ReceiptFromStore/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.4

  auth:
    container_name: auth
    restart: always
    build:
      context: ./auth
    ports:
      - "3005:3005"
    depends_on:
      - keepslip-db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=KeepSlipDB
      - MYSQL_HOST=172.28.1.10
      - MYSQL_PORT=3306
    volumes:
      - /usr/src/app/node_modules
      - ./auth/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.5

  client:
    container_name: client
    restart: always
    build:
      context: ./client
    ports:
      - "3000:3000"
    links:
      - keepslip-db
      - keepslip-nginx
      - service
      - smart-contract
      - the-revenue-department
      - receipt-from-store
      - auth
    volumes:
      - /usr/src/app/.next
      - /usr/src/app/node_modules
      - ./client/:/usr/src/app/
    networks:
      keepslip_network:
        ipv4_address: 172.28.1.6

networks:
  keepslip_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
