POST http://35.247.154.183:3007/api/auth/customer-login
Content-Type: application/json

{
    "username": "Surasith",
    "password": "1234"
}

###
POST http://35.247.154.183:3007/api/auth/store-login
Content-Type: application/json

{
    "username": "A-HOST",
    "password": "12345"
}

###
DELETE http://35.247.154.183:3007/api/auth/logout